---
- name: Deploy haproxy load balancer
  hosts: load_balancers
  gather_facts: false 
  tags:
    - load_balancers
  become: true
  roles:
    - role: haproxy
      vars:
        load_balancer_packages:
        - haproxy
