- name: get ip
  hosts: database_servers
  connection: ssh
  gather_facts: yes
  tasks:
    - name: get ip
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']
      
        